djangoapp/api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    path('expenses/', views.DashbordView.as_view(), name='expense-list'),
]

djangoapp/expenses/urls.py
from django.urls import path
from expenses import views

app_name = 'expense'

urlpatterns = [
    # Expenses URLs
    path('', views.index, name='index' ),
    path('expense/<int:expense_id>/detail', views.expense, name='expense' ),
    path('expense/<int:expense_id>/update', views.expense_update, name='expense_update' ),#type:ignore
    path('expense/<int:expense_id>/delete', views.expense_delete, name='expense_delete' ),#type:ignore
    path('expense/<int:expense_id>/approved/', views.expense_approved, name='approved'), #type:ignore
    path('expense/<int:expense_id>/recused/', views.recused, name='recused'), #type:ignore
    path('expense/<str:username>/filter_per_user/', views.filter_per_user, name='filter_per_user'), 
    path('expense/create/', views.create_expense, name='create'),


    
    # Search
    path('search/', views.search, name='search'), 
    
    # User URLs
    path('user/register/', views.register, name='register'),
    path('user/complete-profile/', views.complete_profile, name='complete_profile'),
    path('user/profile/<str:username>/', views.profile, name='profile'), #type:ignore
    path('user/update/', views.user_update, name='user_update'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/reports/', views.reports, name='reports'),
    path('user/chose/', views.chose_enterprise_or_user, name='chose'),

    # Enterprise URLs
    path('enterprise/register/', views.register_enterprise, name='register_enterprise'),
    path('enterprise/update/', views.update_enterprise, name='update_enterprise'),
    
    # Cycles URLs
    path('ciclos/', views.cycles, name='cycles'), #type:ignore
    path('ciclo/<int:cycle_id>/detail', views.cycle, name='cycle'), #type:ignore
    path('ciclos/create/', views.create_cycle, name='create_cycle'),
    path('ciclos/<int:cycle_id>/close/', views.close_cycle, name='close_cycle'), # type:ignore
    path('ciclos/<int:cycle_id>/open/', views.open_cycle, name='open_cycle'), #type:ignore
    path('ciclos/<int:cycle_id>/update/', views.cycle_update, name='cycle_update'),
    path('ciclos/<int:cycle_id>/delete/', views.cycle_delete, name='cycle_delete'),


    path('dashbords/', views.dashbords, name='dashbords'),

    # Teams URLs
    path('equipes/', views.teams, name='teams'), #type:ignore
    path('equipe/<int:team_id>/', views.team, name='team'), #type:ignore
    path('equipes/create_team', views.create_team, name='create_team'), #type:ignore
    path('equipe/<int:team_id>/update/', views.team_update, name='team_update'),
    path('equipe/<int:team_id>/delete/', views.team_delete, name='team_delete'),
    path('equipe/<int:team_id>/join_team/', views.join_team, name='join_team'),
    path('equipe/<int:team_id>/exit_team/', views.exit_team, name='exit_team'),
    path('equipe/<int:team_id>/invite_member/', views.invite_member, name='invite_member'),
    path('equipe/<int:team_id>/user/<int:user_id>/remove_member', views.remove_member, name='remove_member'),
    path('convite/<uuid:token>/', views.accept_invite, name='accept_invite'),
]


djangoapp/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # Para importar coisas do settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('expenses.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path("billing/", include("billings.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoapp/expenses/models/state.py
from django.db import models

class State(models.Model):
    class Meta:
        verbose_name = 'Estado'
        verbose_name_plural = 'Estados'
    
    name = models.CharField(
                    max_length=30,
                    unique=True,
                            )
    
    uf_name = models.CharField(
                    max_length=2,
                    unique=True
                )
    
    def __str__(self) -> str:
        return f'{self.name}-{self.uf_name}'

djangoapp/expenses/views/cycle_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from expenses.form import CreateCycle, Cycle

@login_required(login_url='expense:login')
def create_cycle(request):
    form_action = reverse('expense:create_cycle')

    if request.method == 'POST':
        
        form = CreateCycle(request.POST)
        
        context = dict(
            form=form,
            form_action=form_action,
        )

        if form.is_valid():        
            cycle = form.save(commit=False) # Grarante que eu não salve na base de dados ainda
            cycle.owner = request.user # Informo para expense.owner que esse contato pertence a esse usuário
            cycle.save()
            messages.success(request, "Ciclo criado com sucesso", extra_tags='fa-circle-check')
            return redirect('expense:cycles')

        return render(
        request,
        'expenses/pages/create_cycle.html',
        context,
        )

    context = dict(
        form=CreateCycle(),
        title_page="CRIAR CICLO",
    )

    return render(
        request,
        'expenses/pages/create_cycle.html',
        context, 
        )

@login_required(login_url='expense:login')
def cycle_update(request, cycle_id):
    cycle = get_object_or_404(Cycle.objects.for_user(request.user).filter(pk=cycle_id))
    
    if request.method == "POST":
        form = CreateCycle(request.POST, instance=cycle)
        if form.is_valid():
            update_cycle = form.save(commit=False)
            update_cycle.owner_id = request.user.id
            update_cycle.save()

            messages.success(request, "Ciclo atualizado com sucesso", extra_tags='fa-circle-check')
            return redirect('expense:cycles')
        
    else:
        form = CreateCycle(
            instance=cycle,
            initial={
                'name': cycle.name,
                'initial_date': cycle.initial_date.strftime('%Y-%m-%d'),
                'end_date': cycle.end_date.strftime('%Y-%m-%d'),
                'initial_km': cycle.initial_km,
                'end_km': cycle.end_km,
                'save_expense_auto': cycle.save_expense_auto,
            })
    
    context = {
        'form': form,
        'cycle':cycle,
        'title_page': "ATUALIZAR CICLO",
    }

    return render(
        request,
        'expenses/pages/create_cycle.html',
        context,      
    )

@login_required(login_url='expense:login')
def cycle_delete(request, cycle_id):
    # 1) Busca o contato pelo id; se não existir (ou show=False), retorna 404
    cycle = get_object_or_404(Cycle.objects.for_user(request.user).filter(pk=cycle_id))
    
    
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        cycle.delete()
        messages.success(request, "Ciclo deletado  com sucesso", extra_tags='fa-circle-check')
        return redirect('expense:cycles')

    return render(
        request,
        'expenses/pages/cycle.html',
        {
            'cycle': cycle,
            'confirmation': confirmation,
            'user': cycle.owner,
        }
    )

djangoapp/expenses/views/cycle_views.py
from django.http import Http404
from expenses.models import Cycle, Expenses
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from utils.calculation import Calculation 
from utils.mixin import PermissionMixin
from django.core.paginator import Paginator



@login_required(login_url='expense:login')
def cycles(request):
    cycles = Cycle.objects.for_user(request.user)
        
    context = {
        'cycles': cycles,
    }

    return render (
        request=request,
        template_name='expenses/pages/cycles.html',
        context=context,
    )

@login_required(login_url='expense:login')
def cycle(request, cycle_id):
    
    cycle = get_object_or_404(Cycle.objects.for_user(request.user).filter(pk=cycle_id))


    expenses = Expenses.objects.for_user(request.user).filter(cycle=cycle)

    
    paginator = Paginator(expenses, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    

    role = PermissionMixin.get_user_role(request.user)
    calculation = Calculation(cycle, expenses).all()

    context = {
        'cycle': cycle,
        'page_obj': page_obj,
        'calculation': calculation,
        'role': role,
    }

    return render (
        request=request,
        template_name='expenses/pages/cycle.html',
        context=context,
    )

def close_cycle(request, cycle_id):

    cicle = get_object_or_404(
        Cycle.objects.for_user(request.user).filter(pk=cycle_id),
        ) 

    if cicle.is_open:
        cicle.is_open = False
        cicle.save()

    return redirect("expense:cycles")
    
    
def open_cycle(request, cycle_id):
    cicle = get_object_or_404(
        Cycle.objects.for_user(request.user).filter(pk=cycle_id),
    ) 
    
    if not cicle.is_open:
        cicle.is_open = True
        cicle.save()

    return redirect("expense:cycles")
    
    

djangoapp/expenses/views/enterprise_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from expenses.form import EnterpriseRegisterForm
from expenses.models import Role, UserEnterpriseRole, UserProfile, EnterPrise

@login_required(login_url='expense:login')
def register_enterprise(request):
    if request.method == 'POST':      
        form = EnterpriseRegisterForm(request.POST)
        
        context = dict(
            form=form,
            # form_action=form_action,         
        )

        if form.is_valid():        
            enterprise = form.save(commit=False)
            enterprise.owner = request.user # fill in the enterprise.owner field with the owner.
            enterprise.save()

            profile = UserProfile.objects.get(user=request.user)
            profile.enterprise = enterprise # fill in the company field with the company created by the user..
            profile.save()

            owner_role = Role.objects.get(name='COMPANY_ADMIN')
            UserEnterpriseRole.objects.create(
                user=request.user,
                enterprise=enterprise,
                role=owner_role,
            )
            
            messages.success(request, "Empresa cadastrada com sucesso")
            return redirect('expense:index')

        return render(
        request,
        'expenses/pages/register_enterprise.html',
        context,
        )

    context = dict(
        form=EnterpriseRegisterForm(),
        title_page="CADASTRAR EMPRESA",   
        is_register_enterprise=True,
    )

    return render(
        request,
        'expenses/pages/register_enterprise.html',
        context, 
        )

@login_required(login_url='expense:login')
def update_enterprise(request):
    enterprise = get_object_or_404(EnterPrise, owner=request.user)

    if request.method == "POST":
        form = EnterpriseRegisterForm(request.POST, instance=enterprise)
        if form.is_valid():
            form.save()

            messages.success(request, "Empresa atualizada com sucesso")
            return redirect('expense:profile', request.user.username)
        
    else:
        form = EnterpriseRegisterForm(
            instance=enterprise,
            initial={
                'name': enterprise.name,
                'cnpj': enterprise.cnpj,
                'plan_type':enterprise.plan_type,
            }
        )

    context = dict(
        form=form,
        title_page="ATUALIZAR DADOS DA  EMPRESA",   
        is_update_enterprise=True,
    )

    return render(
        request,
        'expenses/pages/update_enterprise.html',
        context, 
    )


djangoapp/expenses/views/expense_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator
from expenses.models import Expenses, ExpenseAudit
from utils.mixin import PermissionMixin


# Create your views here.
@login_required(login_url='expense:login')
def index(request):
    expenses = Expenses.objects.for_user(request.user)
    paginator = Paginator(expenses, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Despesas - ',
    }

    return render(
        request=request,
        template_name='expenses/pages/index.html',
        context=context,
    )

@login_required(login_url='expense:login')
def expense(request, expense_id):
    single_expense = get_object_or_404(Expenses.objects.for_user(request.user), pk=expense_id)
    last_alert = single_expense.alerts_recused.last() # Pega o ultimo alerta # type:ignore
    role = PermissionMixin.get_user_role(request.user)
    
    qs_audits = (
        ExpenseAudit.objects
        .filter(expense=single_expense)
        .order_by('created_at')
    )   
    list_audits = list(qs_audits)
    last_audit = list_audits[-1] if list_audits else None

    context = {
        'expense': single_expense,
        'alert': last_alert,
        'role': role,
        'last_audit': last_audit,
        'audits': list_audits,
    }

    return render (
        request=request,
        template_name='expenses/pages/expense.html',
        context=context,
    )
    
@login_required(login_url='expense:login')
def dashbords(request):
    print(f'SESSION: {request.session.items()}')
    if PermissionMixin.is_company_admin(request.user):

        context = dict(
            is_dashbord=True,
        )
        return render (
            request=request,
            template_name='expenses/pages/dashbords_admin.html',
            context=context,
        )
    
    elif PermissionMixin.is_manager(request.user):
        context = dict(
            is_dashbord=True,
        )
        return render (
            request=request,
            template_name='expenses/pages/dashbords_manager.html',
            context=context,
        )
    elif PermissionMixin.is_operator(request.user):
        context = dict(
            is_dashbord=True,
        )
        return render (
            request=request,
            template_name='expenses/pages/dashbords_operator.html',
            context=context,
        )
    
@login_required(login_url='expense:login')
def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('expense:index')

    expenses = Expenses.objects.for_user(request.user)
    page_obj = (
                expenses
                .filter(
                    Q(supply__icontains=search_value) |
                    Q(city__icontains=search_value) |
                    Q(nf__icontains=search_value) |
                    Q(category__name__icontains=search_value) |
                    Q(owner_expenses__first_name__icontains=search_value)
                )
                .order_by('-id')
            )
    
    paginator = Paginator(page_obj, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = dict(
        page_obj=page_obj,
        site_title='Search - '
    )
    return render(
        request,
        'expenses/pages/index.html',
        context,
    )

djangoapp/expenses/views/expenses_filter.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from expenses.models import Expenses
from utils.mixin import PermissionMixin
from utils.decorators import is_manager_or_company_admin

# Create your views here.
@login_required(login_url='expense:login')
@is_manager_or_company_admin
def filter_per_user(request, username):
    User = get_user_model()

    enterprise = PermissionMixin.get_user_enterprise(request.user)
    employee = get_object_or_404(User, username=username, profile__enterprise=enterprise)
    expenses = Expenses.objects.for_user(request.user).filter(owner_expenses=employee)

    paginator = Paginator(expenses, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Despesas - ',
    }

    return render(
        request=request,
        template_name='expenses/pages/index.html',
        context=context,
    )

djangoapp/expenses/templates/expenses/pages/complete_profile.html
{% extends "expenses/base.html" %}
{% load static %}


{% block content %}
<div class="background-image-blue">
    <div class="complete-profile-container">
        <div class="container-logo-text-flext background-transiction-blue">
            <img 
                src="{% static "expenses/images/logo_transparent_512.png" %}" 
                alt="logo" class="logo-image">
            </img>
            <h1 class="login-pitch-title">ExpenseFlow</h1>
        </div>

        <div class="contact-links">
            <a class='btn btn-link ' href="{% url "expense:chose" %}">
                <i class="fa-solid fa-arrow-left"></i>
                VOLTAR
            </a>
        </div>
        
        <div class="flex-frame-login-form">
            <div class="form-wrapper flex-frame max-width-form-profile form-complete-form">
                <h2 class="expense-detail-title expense-info-title">
                    <i class="fa-solid fa-user"></i>
                    {{title_page}}
                </h2>
                {% include "expenses/partials/_user-form.html" %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

djangoapp/expenses/templates/expenses/pages/create_team.html
{% extends "expenses/base.html" %}

{% block content %}
    <div class="contact-links back-button">
        <a class='btn btn-link ' href="{% url "expense:teams" %}">
            <i class="fa-solid fa-arrow-left"></i>
            VOLTAR
        </a>
    </div>

    <div class="flex-frame-login-form">
        <div class="form-wrapper flex-frame max-width-form-profile
            margin-top-biggest padding-forms form-create-team">
            <h2 class="expense-detail-title expense-info-title">
                <i class="fa-solid fa-people-group"></i>
                {{title_page | default:"SEM TITULO"}}
            </h2>
            <form action="{{form_action}}" method="post"> 
                {% csrf_token %}
                
                <div class="form-content">

                    {% for field in form %}
                    
                    {% if field.name == 'cost_center'%}
                        <div class="form-row-two-columns">
                    {% endif %}

                        <div class="form-group">  
                        
                            <label for="{{field.id_for_label}}">{{field.label}}</label>
                            {{field}}
                            {{field.errors}}

                        {% if field.help_text %}
                            <p class="help-text">
                                {{field.help_text}}
                            </p>
                        {% endif %}
                    </div>

                    
                    {% if field.name == 'enterprise' %}
                        </div>
                    {% endif %}

                    {% endfor %}
                </div>

            {% if form.non_field_errors %}
            <div class="form-content">
                <div class="form-group">
                    <div class="message error">
                        {{form.non_field_errors}}
                    </div>         
                </div>
            </div>
            {% endif %}
            
            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type='submit'>
                        {{title_page}}
                    </button>                   
                </div>
            </div>
        </div>
{% endblock content %}

djangoapp/expenses/templates/expenses/pages/team.html
{% extends "expenses/base.html" %}

{% block content %}

<div class="expense-detail-container">
    {% if messages %}
        <div class="message-container">
            {% for message in messages %}
                {% if message.level_tag == 'success' or message.level_tag == 'error'  %}
                    <div class="message {{message.level_tag}}">
                        <i class="fa-solid {{message.extra_tags}} fa-2x"></i>
                        <p class="message-text">
                            {{message}}
                        </p>         
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
    <h1 class="expense-detail-title expense-info-title">
        <i class="fa-solid fa-people-group"></i>
        {{team.name}}
    </h1>

    <div class="contact-links">
        <a class='btn btn-link ' href="{% url "expense:teams" %}">
            <i class="fa-solid fa-arrow-left"></i>
            VOLTAR
        </a>
        <a class='btn btn-link' href="{% url "expense:team_update" team.pk %}">
            <i class="fa-solid fa-pen-to-square"></i>
            ATUALIZAR
        </a>
        <a class='btn btn-link btn-approved' href="{% url "expense:invite_member" team.pk %}">
            <i class="fa-solid fa-user-plus"></i>
            ADICIONAR MEMBRO
        </a>
        {% if company_admin %}
            {% if user.profile.team != team %}
                <a class='btn btn-link  btn-approved ' href="{% url "expense:join_team" team.pk %}">
                    ENTRAR NA EQUIPE
                </a>
            {% else %}
                <a class='btn btn-link btn-delete' href="{% url "expense:exit_team" team.pk %}">
                    SAIR DA EQUIPE
                </a>
            {% endif %}
        {% endif %}
    </div>
    

    <div class="expense-detail-grid">

        <!-- Card de Informações Básicas -->
        <div class="expense-description-card">
            <h2 class="expense-info-title">
                <i class="fa-solid fa-circle-info"></i>
                Informações da Equipe
            </h2>
            <div class="grid-four-columns center-text">

                <div class="expense-info-item">
                    <span class="expense-info-label">
                        <i class="fa-solid fa-building"></i>
                        Empresa:
                    </span>
                    <span class="expense-info-value">{{team.enterprise}}</span>
                </div>

                <div class="expense-info-item">
                    <span class="expense-info-label">
                        <i class="fa-solid fa-user-tie"></i>
                        Gestor Responsável
                    </span>
                    <span class="expense-info-value">{{team.team_manager.get_full_name|default:"Sem gestor"}}</span>
                </div>
            
                <div class="expense-info-item">
                    <span class="expense-info-label">
                        <i class="fa-solid fa-sitemap"></i>
                        Centro de Custo
                    </span>
                    <span class="expense-info-value">{{team.cost_center}}</span>
                </div>
                
                <div class="expense-info-item">
                    <span class="expense-info-label">
                        <i class="fa-solid fa-clock"></i>
                        Status
                    </span>
                    <span class="expense-info-value">
                        {% if team.is_active %}
                            <span class="expense-badge expense-approved">
                                <i class="fa-solid fa-unlock"></i>
                                Ativa
                            </span>
                        {% else %}  
                            <span class="expense-badge expense-recused">
                                <i class="fa-solid fa-lock"></i>
                                Inativa
                            </span>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>

        <div class="expense-description-card">
            <h2 class="expense-info-title">
            <i class="fa-solid fa-people-group"></i>            
                Membros da Equipe
            </h2>
            <div class="grid-four-columns">
                
                {% for member in members %}
                <div class="expense-info-item center-text user-member">
                    <a class="remove-text-decoration" href="{% url "expense:profile" member.user.username %}">
                        <p class="icon-container-user">
                            <i class="fa-solid fa-user fa-2x"></i>
                        </p>
                        <p class="expense-info-value">
                            {{member.user.first_name}} {{member.user.last_name}}
                        </p>
                    </a>
                </div>

                {% empty %}
                    <p class="none-member-text">Nenhum membro na equipe</p>
                {% endfor %}
            </div>
        </div>     
    </div>

    
    {% if page_obj %}
    <div class='responsive-table content'>
        <table class='contacts-table'>
            <caption>
                <h2 class="expense-detail-title expense-info-title">
                    <i class="fa-solid fa-cart-shopping"></i>
                    Todas as despesas da equipe
                </h2>
            </caption>
            <thead>
                <tr class='table-row table-row-header'>
                    <th class='table-header'></th>
                    <th class='table-header'>Solicitante</th>
                    <th class='table-header'>Categoria</th>
                    <th class='table-header'>Status</th>
                    <th class='table-header'>Fornecedor</th>
                    <th class='table-header'>Cidade</th>
                    <th class='table-header'>Data</th>
                    <th class='table-header'>Valor Total</th>
                </tr>
            </thead>

            <tbody>
                {% for expense in page_obj %}
                    <tr class='table-row'>
                        
                        <td class="table-cel">
                            <a class='table-link' href="{% url "expense:expense" expense.id %}">
                            <i class="fa-solid fa-up-right-from-square" title="Abrir despesa"></i>
                            </a>
                        </td>
                        <td class="table-cel">         
                            {{expense.owner_expenses.first_name}} {{expense.owner_expenses.last_name}}
                        </td>
                        
                        <td class="table-cel">
                            {{expense.category}}
                        </td>

                        <td class="table-cel">
                        {% if expense.status.name == "PENDENTE" %}
                            <span class="icon-status-pending">
                                <i class="fa-solid fa-hourglass-half"></i>
                            </span>
                        {% elif expense.status.name == "APROVADO" %}
                            <span class="icon-status-approved">
                                <i class="fa-regular fa-circle-check"></i>
                            </span>
                        {% else %}
                            <span class="icon-status-recused">
                                <i class="fa-regular fa-circle-xmark"></i>
                            </span>
                        {% endif %}
                        </td>
                        
                        <td class="table-cel">      
                            {{expense.supply}}
                        </td>
                        
                        <td class="table-cel">
                            {{expense.city}}
                        </td>
                        
                        <td class="table-cel">
                            {{expense.date|date:"d/m/Y" }}
                        </td>

                        <td class="table-cel">
                            R$ {{expense.value}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% include "expenses/partials/_pagination.html" %}
    </div>
{% else %}
    <div class="none-expense-container">
        <h1 class="none-expense-text">
            Nenhuma despesa nesta equipe
        </h1>
    </div>
{% endif %}

    {% if company_admin %}
        <form action="{% url "expense:team_delete" team.id %}" method='POST'>
            {% csrf_token %}

            {% if confirmation == 'no' %}
                <input type="hidden" name="confirmation" value="yes">
                <button 
                id='delete'
                class="btn btn-link btn-delete"
                type='submit'>
                    CONFIRMA A EXCLUSÃO ?
                </button>            
            {% else %}
                <button 
                class="btn btn-link btn-delete"
                onclick='backToDeleteButton()'>
                    <i class="fa-solid fa-trash"></i>
                    DELETAR EQUIPE
                </button>            
            {% endif %}
        {% endif %}
    </form>
</div>

<script>
    
    window.addEventListener('DOMContentLoaded', function (){
    {% if confirmation == 'no' %}
        const button = document.getElementById('delete');
        
        if (button) {
            button.scrollIntoView({behavior: 'smooth', block: 'center'})
        }
    {% endif %} 
    });

</script>
{% endblock content %}