djangoapp/api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    path('expenses/', views.DashbordView.as_view(), name='expense-list'),
]

djangoapp/expenses/urls.py
from django.urls import path
from expenses import views

app_name = 'expense'

urlpatterns = [
    # Expenses URLs
    path('', views.index, name='index' ),
    path('expense/<int:expense_id>/detail', views.expense, name='expense' ),
    path('expense/<int:expense_id>/update', views.expense_update, name='expense_update' ),#type:ignore
    path('expense/<int:expense_id>/delete', views.expense_delete, name='expense_delete' ),#type:ignore
    path('expense/<int:expense_id>/approved/', views.expense_approved, name='approved'), #type:ignore
    path('expense/<int:expense_id>/recused/', views.recused, name='recused'), #type:ignore
    path('expense/<str:username>/filter_per_user/', views.filter_per_user, name='filter_per_user'), 
    path('expense/create/', views.create_expense, name='create'),


    
    # Search
    path('search/', views.search, name='search'), 
    
    # User URLs
    path('user/register/', views.register, name='register'),
    path('user/complete-profile/', views.complete_profile, name='complete_profile'),
    path('user/profile/<str:username>/', views.profile, name='profile'), #type:ignore
    path('user/update/', views.user_update, name='user_update'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/reports/', views.reports, name='reports'),
    path('user/chose/', views.chose_enterprise_or_user, name='chose'),

    # Enterprise URLs
    path('enterprise/register/', views.register_enterprise, name='register_enterprise'),
    path('enterprise/update/', views.update_enterprise, name='update_enterprise'),
    
    # Cycles URLs
    path('ciclos/', views.cycles, name='cycles'), #type:ignore
    path('ciclo/<int:cycle_id>/detail', views.cycle, name='cycle'), #type:ignore
    path('ciclos/create/', views.create_cycle, name='create_cycle'),
    path('ciclos/<int:cycle_id>/close/', views.close_cycle, name='close_cycle'), # type:ignore
    path('ciclos/<int:cycle_id>/open/', views.open_cycle, name='open_cycle'), #type:ignore
    path('ciclos/<int:cycle_id>/update/', views.cycle_update, name='cycle_update'),
    path('ciclos/<int:cycle_id>/delete/', views.cycle_delete, name='cycle_delete'),


    path('dashbords/', views.dashbords, name='dashbords'),

    # Teams URLs
    path('equipes/', views.teams, name='teams'), #type:ignore
    path('equipe/<int:team_id>/', views.team, name='team'), #type:ignore
    path('equipes/create_team', views.create_team, name='create_team'), #type:ignore
    path('equipe/<int:team_id>/update/', views.team_update, name='team_update'),
    path('equipe/<int:team_id>/delete/', views.team_delete, name='team_delete'),
    path('equipe/<int:team_id>/join_team/', views.join_team, name='join_team'),
    path('equipe/<int:team_id>/exit_team/', views.exit_team, name='exit_team'),
    path('equipe/<int:team_id>/invite_member/', views.invite_member, name='invite_member'),
    path('equipe/<int:team_id>/user/<int:user_id>/remove_member', views.remove_member, name='remove_member'),
    path('convite/<uuid:token>/', views.accept_invite, name='accept_invite'),
]


djangoapp/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # Para importar coisas do settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('expenses.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path("billing/", include("billings.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoapp/expenses/models/state.py
from django.db import models

class State(models.Model):
    class Meta:
        verbose_name = 'Estado'
        verbose_name_plural = 'Estados'
    
    name = models.CharField(
                    max_length=30,
                    unique=True,
                            )
    
    uf_name = models.CharField(
                    max_length=2,
                    unique=True
                )
    
    def __str__(self) -> str:
        return f'{self.name}-{self.uf_name}'

djangoapp/expenses/views/cycle_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from expenses.form import CreateCycle, Cycle

@login_required(login_url='expense:login')
def create_cycle(request):
    form_action = reverse('expense:create_cycle')

    if request.method == 'POST':
        
        form = CreateCycle(request.POST)
        
        context = dict(
            form=form,
            form_action=form_action,
        )

        if form.is_valid():        
            cycle = form.save(commit=False) # Grarante que eu não salve na base de dados ainda
            cycle.owner = request.user # Informo para expense.owner que esse contato pertence a esse usuário
            cycle.save()
            messages.success(request, "Ciclo criado com sucesso", extra_tags='fa-circle-check')
            return redirect('expense:cycles')

        return render(
        request,
        'expenses/pages/create_cycle.html',
        context,
        )

    context = dict(
        form=CreateCycle(),
        title_page="CRIAR CICLO",
    )

    return render(
        request,
        'expenses/pages/create_cycle.html',
        context, 
        )

@login_required(login_url='expense:login')
def cycle_update(request, cycle_id):
    cycle = get_object_or_404(Cycle.objects.for_user(request.user).filter(pk=cycle_id))
    
    if request.method == "POST":
        form = CreateCycle(request.POST, instance=cycle)
        if form.is_valid():
            update_cycle = form.save(commit=False)
            update_cycle.owner_id = request.user.id
            update_cycle.save()

            messages.success(request, "Ciclo atualizado com sucesso", extra_tags='fa-circle-check')
            return redirect('expense:cycles')
        
    else:
        form = CreateCycle(
            instance=cycle,
            initial={
                'name': cycle.name,
                'initial_date': cycle.initial_date.strftime('%Y-%m-%d'),
                'end_date': cycle.end_date.strftime('%Y-%m-%d'),
                'initial_km': cycle.initial_km,
                'end_km': cycle.end_km,
                'save_expense_auto': cycle.save_expense_auto,
            })
    
    context = {
        'form': form,
        'cycle':cycle,
        'title_page': "ATUALIZAR CICLO",
    }

    return render(
        request,
        'expenses/pages/create_cycle.html',
        context,      
    )

@login_required(login_url='expense:login')
def cycle_delete(request, cycle_id):
    # 1) Busca o contato pelo id; se não existir (ou show=False), retorna 404
    cycle = get_object_or_404(Cycle.objects.for_user(request.user).filter(pk=cycle_id))
    
    
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        cycle.delete()
        messages.success(request, "Ciclo deletado  com sucesso", extra_tags='fa-circle-check')
        return redirect('expense:cycles')

    return render(
        request,
        'expenses/pages/cycle.html',
        {
            'cycle': cycle,
            'confirmation': confirmation,
            'user': cycle.owner,
        }
    )

djangoapp/expenses/views/cycle_views.py
from django.http import Http404
from expenses.models import Cycle, Expenses
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from utils.calculation import Calculation 
from utils.mixin import PermissionMixin
from django.core.paginator import Paginator



@login_required(login_url='expense:login')
def cycles(request):
    cycles = Cycle.objects.for_user(request.user)
        
    context = {
        'cycles': cycles,
    }

    return render (
        request=request,
        template_name='expenses/pages/cycles.html',
        context=context,
    )

@login_required(login_url='expense:login')
def cycle(request, cycle_id):
    
    cycle = get_object_or_404(Cycle.objects.for_user(request.user).filter(pk=cycle_id))


    expenses = Expenses.objects.for_user(request.user).filter(cycle=cycle)

    
    paginator = Paginator(expenses, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    

    role = PermissionMixin.get_user_role(request.user)
    calculation = Calculation(cycle, expenses).all()

    context = {
        'cycle': cycle,
        'page_obj': page_obj,
        'calculation': calculation,
        'role': role,
    }

    return render (
        request=request,
        template_name='expenses/pages/cycle.html',
        context=context,
    )

def close_cycle(request, cycle_id):

    cicle = get_object_or_404(
        Cycle.objects.for_user(request.user).filter(pk=cycle_id),
        ) 

    if cicle.is_open:
        cicle.is_open = False
        cicle.save()

    return redirect("expense:cycles")
    
    
def open_cycle(request, cycle_id):
    cicle = get_object_or_404(
        Cycle.objects.for_user(request.user).filter(pk=cycle_id),
    ) 
    
    if not cicle.is_open:
        cicle.is_open = True
        cicle.save()

    return redirect("expense:cycles")
    
    

djangoapp/expenses/views/enterprise_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from expenses.form import EnterpriseRegisterForm
from expenses.models import Role, UserEnterpriseRole, UserProfile, EnterPrise

@login_required(login_url='expense:login')
def register_enterprise(request):
    if request.method == 'POST':      
        form = EnterpriseRegisterForm(request.POST)
        
        context = dict(
            form=form,
            # form_action=form_action,         
        )

        if form.is_valid():        
            enterprise = form.save(commit=False)
            enterprise.owner = request.user # fill in the enterprise.owner field with the owner.
            enterprise.save()

            profile = UserProfile.objects.get(user=request.user)
            profile.enterprise = enterprise # fill in the company field with the company created by the user..
            profile.save()

            owner_role = Role.objects.get(name='COMPANY_ADMIN')
            UserEnterpriseRole.objects.create(
                user=request.user,
                enterprise=enterprise,
                role=owner_role,
            )
            
            messages.success(request, "Empresa cadastrada com sucesso")
            return redirect('expense:index')

        return render(
        request,
        'expenses/pages/register_enterprise.html',
        context,
        )

    context = dict(
        form=EnterpriseRegisterForm(),
        title_page="CADASTRAR EMPRESA",   
        is_register_enterprise=True,
    )

    return render(
        request,
        'expenses/pages/register_enterprise.html',
        context, 
        )

@login_required(login_url='expense:login')
def update_enterprise(request):
    enterprise = get_object_or_404(EnterPrise, owner=request.user)

    if request.method == "POST":
        form = EnterpriseRegisterForm(request.POST, instance=enterprise)
        if form.is_valid():
            form.save()

            messages.success(request, "Empresa atualizada com sucesso")
            return redirect('expense:profile', request.user.username)
        
    else:
        form = EnterpriseRegisterForm(
            instance=enterprise,
            initial={
                'name': enterprise.name,
                'cnpj': enterprise.cnpj,
                'plan_type':enterprise.plan_type,
            }
        )

    context = dict(
        form=form,
        title_page="ATUALIZAR DADOS DA  EMPRESA",   
        is_update_enterprise=True,
    )

    return render(
        request,
        'expenses/pages/update_enterprise.html',
        context, 
    )


djangoapp/expenses/views/expense_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator
from expenses.models import Expenses, ExpenseAudit
from utils.mixin import PermissionMixin


# Create your views here.
@login_required(login_url='expense:login')
def index(request):
    expenses = Expenses.objects.for_user(request.user)
    paginator = Paginator(expenses, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Despesas - ',
    }

    return render(
        request=request,
        template_name='expenses/pages/index.html',
        context=context,
    )

@login_required(login_url='expense:login')
def expense(request, expense_id):
    single_expense = get_object_or_404(Expenses.objects.for_user(request.user), pk=expense_id)
    last_alert = single_expense.alerts_recused.last() # Pega o ultimo alerta # type:ignore
    role = PermissionMixin.get_user_role(request.user)
    
    qs_audits = (
        ExpenseAudit.objects
        .filter(expense=single_expense)
        .order_by('created_at')
    )   
    list_audits = list(qs_audits)
    last_audit = list_audits[-1] if list_audits else None

    context = {
        'expense': single_expense,
        'alert': last_alert,
        'role': role,
        'last_audit': last_audit,
        'audits': list_audits,
    }

    return render (
        request=request,
        template_name='expenses/pages/expense.html',
        context=context,
    )
    
@login_required(login_url='expense:login')
def dashbords(request):
    print(f'SESSION: {request.session.items()}')
    if PermissionMixin.is_company_admin(request.user):

        context = dict(
            is_dashbord=True,
        )
        return render (
            request=request,
            template_name='expenses/pages/dashbords_admin.html',
            context=context,
        )
    
    elif PermissionMixin.is_manager(request.user):
        context = dict(
            is_dashbord=True,
        )
        return render (
            request=request,
            template_name='expenses/pages/dashbords_manager.html',
            context=context,
        )
    elif PermissionMixin.is_operator(request.user):
        context = dict(
            is_dashbord=True,
        )
        return render (
            request=request,
            template_name='expenses/pages/dashbords_operator.html',
            context=context,
        )
    
@login_required(login_url='expense:login')
def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('expense:index')

    expenses = Expenses.objects.for_user(request.user)
    page_obj = (
                expenses
                .filter(
                    Q(supply__icontains=search_value) |
                    Q(city__icontains=search_value) |
                    Q(nf__icontains=search_value) |
                    Q(category__name__icontains=search_value) |
                    Q(owner_expenses__first_name__icontains=search_value)
                )
                .order_by('-id')
            )
    
    paginator = Paginator(page_obj, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = dict(
        page_obj=page_obj,
        site_title='Search - '
    )
    return render(
        request,
        'expenses/pages/index.html',
        context,
    )

djangoapp/expenses/views/expenses_filter.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from expenses.models import Expenses
from utils.mixin import PermissionMixin
from utils.decorators import is_manager_or_company_admin

# Create your views here.
@login_required(login_url='expense:login')
@is_manager_or_company_admin
def filter_per_user(request, username):
    User = get_user_model()

    enterprise = PermissionMixin.get_user_enterprise(request.user)
    employee = get_object_or_404(User, username=username, profile__enterprise=enterprise)
    expenses = Expenses.objects.for_user(request.user).filter(owner_expenses=employee)

    paginator = Paginator(expenses, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Despesas - ',
    }

    return render(
        request=request,
        template_name='expenses/pages/index.html',
        context=context,
    )

djangoapp/expenses/templates/expenses/partials/_head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" type="image/png" href="{% static 'expenses/images/logo_transparent_512.png' %}">
<link rel="stylesheet" href="{% static "expenses/css/remedy.css" %}">
<link rel="stylesheet" href="{% static "expenses/css/style.css" %}">
{% if is_dashbord %}
<script type='module' src="{% static "expenses/javascript/charts.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endif %}
{% if is_expense_form %}
<script type='module' src="{% static "expenses/javascript/dragDrop.js" %}"></script>
{% endif %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script type='module' src="{% static "expenses/javascript/disableMessage.js" %}"></script>
<title>ExpenseFlow</title>

djangoapp/expenses/templates/expenses/partials/_pagination.html
{% if page_obj %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1&q={{request.GET.q.strip}}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&q={{request.GET.q.strip}}">Anterior</a>
        {% endif %}

        <span class="current">
            Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&q={{request.GET.q.strip}}">Próxima</a>
            <a href="?page={{ page_obj.paginator.num_pages }}&q={{request.GET.q.strip}}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}

djangoapp/expenses/templates/expenses/partials/_sidebar.html
{% load static %}
<nav id="mySidepanel" class="sidebar">
    {% if user.is_authenticated %}
        <div class="container-logo-text-flext sidebar-logo-text-flex">
            <img 
                src="{% static "expenses/images/logo_transparent_512.png" %}" 
                alt="logo" class="logo-image-sidebar">
            </img>
            <h1 class="sidebar-pitch-title">ExpenseFlow</h1>
        </div>
        <a href="javascript:void(0)" id='close' class="menu-link" onclick="closeNav()">
            <i class="fa-solid fa-circle-xmark"></i>
            Fechar Menu
        </a>
        <a href="{% url "expense:index" %}" class="menu-link">
            <i class="fa-solid fa-house"></i>
                Home
        </a>
        {% if not operator %}
        <a href="{% url "expense:teams"%}" class="menu-link">
            <i class="fa-solid fa-people-group"></i>
                Minhas Equipes
        </a>
        {% endif %}
        <a href="{% url "expense:cycles"%}" class="menu-link">
            <i class="fa-solid fa-arrows-spin"></i>
                    Meus ciclos
        </a>
        <a href="{% url "expense:create" %}" class="menu-link">
            <i class="fa-solid fa-cart-shopping"></i>
                    Adicionar despesa
        </a>
        <a href="{% url "expense:dashbords" %}" class="menu-link">
            <i class="fa-solid fa-chart-pie"></i>
                    Dashbords
        </a>
        <a href="{% url "expense:reports"%}" class="menu-link">
            <i class="fa-solid fa-file-lines"></i>
                    Relatórios
        </a>
        <a href="{% url "expense:profile" user.username %}" class="menu-link">
            <i class="fa-solid fa-user"></i>
                    Meu Perfil
        </a>
        <a href="{% url "expense:logout" %}" class="menu-link">
            <i class="fa-solid fa-right-from-bracket"></i>
                    Logout
        </a>
    {% else %}
        <a href="{% url "expense:register" %}" class="menu-link">
                    Cadastrar
        </a>
        <a href="{% url "expense:login" %}" class="menu-link">
                    Login
        </a>
    {% endif %}
</nav>
<button class="openbtn" onclick="openNav()">&#9776; Abrir Menu</button>

<script>
        /* Set the width of the sidebar to 250px (show it) */
    function openNav() {
        const sidebar =document.getElementById("mySidepanel");
        const mainContent = document.getElementById("index");
        const closeBtn = document.getElementById("close");
        const openbtn = document.querySelector(".openbtn");
        

    
        if (window.innerWidth <= 768) {
            
            sidebar.style.width = "100%";
            sidebar.style.height = "auto";
            sidebar.style.position = "relative";
            sidebar.style.display = "flex";
            sidebar.style.flexDirection = "row";
            sidebar.style.boxShadow = "0 2px 10px rgba(0, 0, 0, 0.2)";
            closeBtn.style.display = "none";
            
            // Não empurra o conteúdo em mobile
            if (mainContent) {
                mainContent.style.marginLeft = "auto";
            }
        } else {
            // Comportamento para desktop - barra lateral
            sidebar.style.width = "200px";
            sidebar.style.height = "100%";
            sidebar.style.position = "fixed";
            sidebar.style.display = "block";
            sidebar.style.flexDirection = "";
            
            // Push content in
            if (mainContent) {
                mainContent.style.marginLeft = "200px";
            }
        }
    }

    
    function closeNav() {
        const sidebar = document.getElementById("mySidepanel");
        const mainContent = document.getElementById("index");
        const openbtn = document.querySelector(".openbtn");
        const closeBtn = document.getElementById("close");

        sidebar.style.width = "0";
        
        if (mainContent) {
            mainContent.style.marginLeft = "auto";
        }
        
        // Resetar others styles
        sidebar.style.display = "";
        sidebar.style.flexDirection = "";
        sidebar.style.position = "";
        sidebar.style.height = "";

        if (window.innerWidth <= 768) {     
            openBtn.style.display = "block";

        }
    }

    /* Ajustar ao redimensionar a janela */
    window.addEventListener('resize', function() {
        const sidebar = document.getElementById("mySidepanel");
        
        // Se a sidebar está aberta (width diferente de 0)
        if (sidebar.style.width && sidebar.style.width !== "0" && sidebar.style.width !== "0px") {
            openNav(); // Reaplicar os estilos corretos para o novo tamanho
        }
    });
</script>

djangoapp/expenses/templates/expenses/partials/_user-form.html
<form action="{{form_action}}" method="post">     
    
    {% csrf_token %}
    
    <div class="form-content">

        {% for field in form %}
            
            {% if field.name == 'first_name'%}
                <div class="form-row-two-columns">
            {% endif %}

            {% if field.name == 'email'%}
                <div class="form-row-two-columns">
            {% endif %}
            
            {% if field.name == 'phone'%}
                <div class="form-row-tree-columns">
            {% endif %}

            {% if field.name == 'password1'%}
                <div class="form-row-two-columns">
            {% endif %}

            {% if field.name == 'bank'%}
                <div class="form-row-two-columns">
            {% endif %}

            {% if field.name == 'account'%}
                <div class="form-row-two-columns">
            {% endif %}

            {% if field.name == 'fleet_number'%}
                <div class="form-row-tree-columns">
            {% endif %}

                <div class="form-group">  
                    
                {% if field.field.widget.input_type == 'checkbox' %}
                    <div>
                        {{field}}
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                    </div>
                {% else %}
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                    {% if field.name == 'username'%}    
                        <div class="input-with-icon">
                            {{field}}
                            <i class="fa-solid fa-user"></i>
                        </div>
                    {% elif field.name == 'password'%}    
                        <div class="input-with-icon">
                            {{field}}
                            <i class="fa-solid fa-lock"></i>
                        </div> 
                    {% elif field.name == 'password1'%}    
                        <div class="input-with-icon">
                            {{field}}
                            <i class="fa-solid fa-lock"></i>
                        </div>
                    {% elif field.name == 'password2'%}    
                        <div class="input-with-icon">
                            {{field}}
                            <i class="fa-solid fa-lock"></i>
                        </div>
                    {% elif field.name == 'email'%}    
                        <div class="input-with-icon">
                            {{field}}
                            <i class="fa-solid fa-envelope"></i>
                        </div>
                    {% else %}
                        {{field}}
                    {% endif %}
                {% endif %}

                {{field.errors}}

                {% if field.help_text %}
                    <p class="help-text">
                        {{field.help_text}}
                    </p>
                {% endif %}
            </div>

            
            {% if field.name == 'last_name' %}
                </div>
            {% endif %}

            {% if field.name == 'username' %}
                </div>
            {% endif %}

            {% if field.name == 'password2' %}
                </div>
            {% endif %}

            {% if field.name == 'city' %}
                </div>
            {% endif %}

            {% if field.name == 'agency' %}
                </div>
            {% endif %}

            {% if field.name == 'account_type' %}
                </div>
            {% endif %}

            {% if field.name == 'fleet_number' %}
                </div>
            {% endif %}

        {% endfor %}
    </div>

    {% if form.non_field_errors %}
    <div class="form-content">
        <div class="form-group">
            <div class="message error">
                {{form.non_field_errors}}
            </div>         
        </div>
    </div>
    {% endif %}
    
    <div class="form-content">
        <div class="form-group">
                {% if is_login %}
                <div class="padding-forms">        
                    <button class="btn enter-btn border-radius-form-login" type='submit'>
                        ENTRAR
                    </button>
                    <a class='btn btn-link btn-approved center-text margin-top-minimum border-radius-form-login' href="{% url "expense:register"%}">
                        CADASTRAR-SE
                    </a> 
                </div>
                {% else %}
                <button class="btn {{green_button}}" type='submit'>
                    {{title_page}}
                </button>                   
                {% endif %}           
        </div>
    </div>